name: CD - Deploy model to Hugging Face

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: ci   # Ne s’exécute que si le workflow CI a réussi

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install -r requirements.txt
          pip install huggingface_hub joblib pandas scikit-learn

      - name: Train model
        run: |
          python src/scripts/training.py

      - name: List model files
        run: ls -lh src/models

      - name: Upload model and app to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.TOKEN_CREDIT_CARD_FRAUD_DETECTION }}
        run: |
          python - <<EOF
          from huggingface_hub import HfApi
          import os

          api = HfApi(token=os.environ["HF_TOKEN"])
          repo_id = "RajaaLE/Credit_Card_Fraud_Dtection_Project"

          # Liste des fichiers à uploader
          files_to_upload = {
              "src/models/final_model_ultra_compressed.joblib": "final_model_ultra_compressed.joblib",
              "app.py": "app.py",
              "requirements.txt": "requirements.txt"
          }

          for local_path, repo_path in files_to_upload.items():
              print(f"Uploading {local_path} to {repo_path}")
              api.upload_file(
                  path_or_fileobj=local_path,
                  path_in_repo=repo_path,
                  repo_id=repo_id,
                  repo_type="space"  # 'space' pour Hugging Face Space
              )
          EOF
